### ISSUE TITLE
Skip EDIFACT 95B UNOC syntax version validation

### ISSUE THREAD

**Issue by sungung** [smooks/smooks-edi-cartridge#127]
I need to parse INVOIC 95B EDIFACT document but UNOC syntax version is 1. Simple hack might be change version before processing the document but is there anyway I can allow Smooks to process version 1 document.

I have tried using local version of EDIFACT-Interchange.dfdl.xsd but EdifactDataProcessorFactory class always getting it from EDIFACT-Common directory.

```
    static {
        try {
            MUSTACHE = new DefaultMustacheFactory().compile("EDIFACT-Common/EDIFACT-Interchange.dfdl.xsd.mustache");
        } catch (Throwable t) {
            throw new SmooksConfigException(t);
        }
    }
```

**Comment by claudemamo** [comment]
Greetings Sungung! With customised EDIFACT schemas, you should use the general-purpose `edi:parser` instead of `edifact:parser`. You need to turn the _EDIFACT-Interchange.dfdl.xsd.mustache_ DFDL template into an actual schema and then reference it from `edi:parser`:

```xml
<smooks-resource-list xmlns="https://www.smooks.org/xsd/smooks-2.0.xsd"
                      xmlns:edifact="https://www.smooks.org/xsd/smooks/edifact-2.0.xsd">

   <edi:parser schemaURI="/EDIFACT-Interchange.dfdl.xsd"/>
   ...
```

We'll investigate supporting other syntax versions.

**Comment by sungung** [comment]
thanks Claude, edi:parser is working like a charm.
