### ISSUE TITLE
EDIFACT D97A doesn't have valid enumerations

### ISSUE THREAD

**Issue by sankethpb** [smooks/smooks-edi-cartridge#185]
Dear All,

We are trying to create EDIFACT DELFOR D97A messages using Smooks 2.0.0-RC1.
We found that few of the qualifier enumerations are not valid for D97A messages. 
Kindly advice on how this could be fixed?

pom.xml is attached for reference, the D97A XSD Schema also has only invalid enum values.

Example:
E1153ReferenceQualifier --> has only one value AAA in the enumeration
E3035PartyQualifier
E7143ItemNumberTypeCoded
E2013FrequencyCoded

Thanks a lot in advance
[pom.xml.txt](https://github.com/smooks/smooks-edi-cartridge/files/8192868/pom.xml.txt)

**Comment by sankethpb** [comment]
@claudemamo kindly request your support here. Thank you in advance.

**Comment by funnydevelop** [comment]
> 

hello ,  i got the same problem with d01b, have you resoloved it ? There were some E1153ReferenceCodeQualifier enum values  were missed ,so that Exception  was occured. such as  RFF - c506 -1153 ，YC1, AVQ  i didn't find them at E1153ReferenceCodeQualifier . If you  deal with  this problem , please help me . thank you. Expect your reply........

**Comment by claudemamo** [comment]
Which version of the cartridge are you using @funnydevelop ?

**Comment by funnydevelop** [comment]
> Which version of the cartridge are you using @funnydevelop ?
 hi, @claudemamo : 
The cartridge version is <smooks.edifact.cartridge.version>2.0.0-RC1</smooks.edifact.cartridge.version>

**Comment by claudemamo** [comment]
The EDIFACT directories are notorious to parse since they are, for the most part, described in free-form text. There are numerous subtleties which the directory parser must take into account before it can generate the DFDL schemas. D96A has some difference/s in the way it describes its code lists which the directory parser doesn't factor in leading to the missing enums.

**Comment by funnydevelop** [comment]
@claudemamo  Do you have solutions to deal with this problem  in other ways  rather than change edifact protocol version (D01B -> D96A .......)？ such as re-build the  smooks-edi-cartridge project  or  wait for the latest  release .

**Comment by funnydevelop** [comment]
@claudemamo  Do you have solutions to deal with this problem  in other ways  rather than change edifact protocol version (D01B -> D96A .......)？ such as re-build the  smooks-edi-cartridge project  or  wait for the latest  release .

**Comment by funnydevelop** [comment]
@claudemamo Do you have solutions to deal with this problem in other ways rather than change edifact protocol version (D01B -> D96A .......)？ such as re-build the smooks-edi-cartridge project or wait for the latest release  etc...

**Comment by bnserig** [comment]
@claudemamo So there is no way to override this ?

**Comment by funnydevelop** [comment]
> 
The XXXX Qualifiers are enum type(e.g. E1153ReferenceCodeQualifier etc....). So, There's no way to override it or extend it within java grammer...  i have an idea ,that's to modify the .class file  and re-package it to jar ,but i didn't try it yet... So , I am not sure this solution is worked fine...

**Comment by sankethpb** [comment]
@funnydevelop based on #125 
We modified the XSD files of D97A to include the required ENUM and added settings in maven to generate the Java Classes and use the generated classes instead of default.
Temporarily this was the only way to use smooks 
Example as given in #125 https://github.com/claudemamo/smooks-java-to-edifact/blob/master/pom.xml#L56-L93
